"""
Category -> ordered list of (column, label, unit) shown in the Advanced
Metrics tab strip. Mirrors core/scorer.py's _MASTER_METRICS pattern.
unit is '' for plain counts/rates, '%' for percentages, 'm' for meters, 's' for seconds.
Column names must exactly match core/advanced/store.py's parquet columns.
"""

CATEGORIES = {
    "passing": {
        "label": "Passing Profile",
        "icon": "🎯",
        "gk_only": False,
        "metrics": [
            ("pass_prog_count_p90", "Progressive passes", ""),
            ("pass_progression_rate_pct", "Progression rate", "%"),
            ("pass_prog_accuracy_pct", "Prog. pass accuracy", "%"),
            ("pass_penetration_gain_m_p90", "Penetration gain", "m"),
            ("pass_into_box_count_p90", "Passes into box", ""),
            ("pass_through_balls_count_p90", "Through balls", ""),
            ("pass_crosses_count_p90", "Crosses completed", ""),
            ("pass_cross_accuracy_pct", "Cross accuracy", "%"),
            ("pass_key_passes_count_p90", "Key passes", ""),
            ("pass_assists_count_p90", "Assists", ""),
            ("pass_median_release_s", "Median release time", "s"),
            ("pass_quick_pct", "Quick passes (<2s)", "%"),
            ("pass_one_touch_pct", "One-touch tempo (<1s)", "%"),
            ("pass_accuracy_pct", "Pass accuracy", "%"),
        ],
    },
    "shooting": {
        "label": "Shooting & Footedness",
        "icon": "⚽",
        "gk_only": False,
        "metrics": [
            ("shoot_shots_count_p90", "Shots", ""),
            ("shoot_goals_count_p90", "Goals", ""),
            ("shoot_sot_count_p90", "Shots on target", ""),
            ("shoot_in_box_count_p90", "Shots in box", ""),
            ("shoot_big_chance_count_p90", "Big-chance shots", ""),
            ("shoot_headed_count_p90", "Headed shots", ""),
            ("shoot_in_box_share_pct", "Shots in box share", "%"),
            ("shoot_mean_distance_m", "Mean shot distance", "m"),
            ("shoot_conversion_pct", "Conversion", "%"),
            ("shoot_accuracy_pct", "Shot accuracy", "%"),
            ("shoot_weak_foot_share_pct", "Weak-foot share", "%"),
            ("shoot_weak_foot_conversion_pct", "Weak-foot conversion", "%"),
        ],
    },
    "defending": {
        "label": "Defending Profile",
        "icon": "🛡️",
        "gk_only": False,
        "metrics": [
            ("def_tackles_total_p90", "Tackles", ""),
            ("def_tackle_success_pct", "Tackle success", "%"),
            ("def_interceptions_total_p90", "Interceptions", ""),
            ("def_blocks_total_p90", "Blocks", ""),
            ("def_clearances_total_p90", "Clearances", ""),
            ("def_recoveries_total_p90", "Recoveries", ""),
            ("def_box_actions_p90", "Box actions", ""),
            ("def_box_tackle_success_pct", "Box tackle success", "%"),
            ("def_box_aerials_won_count_p90", "Box aerials won", ""),
            ("def_box_aerial_success_pct", "Box aerial success", "%"),
            ("def_clearance_distance_m_p90", "Clearance distance", "m"),
            ("def_channel_actions_p90", "Channel actions", ""),
            ("def_channel_tackle_success_pct", "Channel tackle success", "%"),
            ("def_flank_actions_p90", "Flank actions", ""),
            ("def_flank_tackle_success_pct", "Flank tackle success", "%"),
            ("def_fouls_box_count_p90", "Fouls in box", ""),
            ("def_fouls_channel_count_p90", "Fouls in channel", ""),
        ],
    },
    "goalkeeping": {
        "label": "Goalkeeping",
        "icon": "🧤",
        "gk_only": True,
        "metrics": [
            ("gk_save_rate_pct", "Save rate", "%"),
            ("gk_saves_count_p90", "Saves", ""),
            ("gk_goals_conceded_count_p90", "Goals conceded", ""),
            ("gk_claims_count_p90", "Claims", ""),
            ("gk_sweeps_count_p90", "Sweeps", ""),
            ("gk_sweep_distance", "Sweep distance", "m"),
            ("gk_distribution_accuracy_pct", "Distribution accuracy", "%"),
            ("gk_plays_short_pct", "Plays short", "%"),
        ],
    },
    "carrying": {
        "label": "Carrying Profile",
        "icon": "🏃",
        "gk_only": False,
        "metrics": [
            ("carry_prog_count_p90", "Progressive carries", ""),
            ("carry_penetration_gain_m_p90", "Carry penetration", "m"),
            ("carry_into_box_count_p90", "Carries into box", ""),
            ("carry_takeons_attempted_p90", "Take-ons attempted", ""),
            ("carry_takeon_success_pct", "Take-on success", "%"),
            ("carry_mean_distance_m", "Mean carry distance", "m"),
            ("carry_angle_bias_index", "Angle bias index", ""),
            ("carry_directness", "Carry directness", ""),
        ],
    },
    "half_spaces": {
        "label": "Half-Spaces",
        "icon": "📐",
        "gk_only": False,
        "metrics": [
            ("hs_receptions_p90", "Receptions", ""),
            ("hs_passes_p90", "Passes from half-space", ""),
            ("hs_prog_passes_p90", "Progressive passes", ""),
            ("hs_progression_rate_pct", "Progression rate", "%"),
            ("hs_carries_p90", "Carries", ""),
            ("hs_prog_carries_p90", "Progressive carries", ""),
            ("hs_takeons_p90", "Take-ons", ""),
            ("hs_takeon_success_pct", "Take-on success", "%"),
            ("hs_key_passes_p90", "Key passes", ""),
            ("hs_shots_p90", "Shots", ""),
            ("hs_into_box_p90", "Into box", ""),
            ("hs_def_actions_p90", "Defensive actions", ""),
            ("hs_tackles_p90", "Tackles", ""),
            ("hs_tackle_success_pct", "Tackle success", "%"),
            ("hs_interceptions_p90", "Interceptions", ""),
            ("hs_recoveries_p90", "Recoveries", ""),
            ("hs_blocks_p90", "Blocks", ""),
            ("hs_aerials_won_p90", "Aerials won", ""),
        ],
    },
    "tempo": {
        "label": "Tempo Control",
        "icon": "⏱️",
        "gk_only": False,
        "metrics": [
            ("tempo_injectors_p90", "Injectors", ""),
            ("tempo_injector_passes_p90", "Injector passes", ""),
            ("tempo_injector_carries_p90", "Injector carries", ""),
            ("tempo_injector_success_pct", "Injector success", "%"),
            ("tempo_resets_p90", "Resets", ""),
            ("tempo_aggression_ratio", "Aggression ratio", ""),
            ("tempo_injectors_into_box_p90", "Injectors into box", ""),
            ("tempo_median_release_s", "Median release", "s"),
            ("tempo_quick_release_pct", "Quick release (<1s)", "%"),
        ],
    },
    "post_recovery": {
        "label": "Post-Recovery",
        "icon": "♻️",
        "gk_only": False,
        "metrics": [
            ("pr_recoveries_p90", "Recoveries", ""),
            ("pr_retention_pct", "Retention", "%"),
            ("pr_prog_pass_pct", "Progressive pass", "%"),
            ("pr_prog_carry_pct", "Progressive carry", "%"),
            ("pr_carry_then_progress_pct", "Carry then progress", "%"),
            ("pr_prog_passes_off_recovery_p90", "Prog. passes off recovery", ""),
            ("pr_prog_carries_off_recovery_p90", "Prog. carries off recovery", ""),
            ("pr_backward_release_pct", "Backward release", "%"),
        ],
    },
    "aerial": {
        "label": "Aerial Duels",
        "icon": "🦅",
        "gk_only": False,
        "metrics": [
            ("aer_duels_count_p90", "Aerial duels", ""),
            ("aer_win_rate_op_pct", "Win rate, open play", "%"),
            ("aer_win_rate_sp_pct", "Win rate, set piece", "%"),
            ("aer_aq_points_per_duel", "AQ points per duel", ""),
            ("aer_duel_quality_pct", "Duel quality", "%"),
            ("aer_retains_plays_pct", "Retains & plays", "%"),
            ("aer_falls_teammate_pct", "Falls to teammate", "%"),
            ("aer_falls_opponent_pct", "Falls to opponent", "%"),
            ("aer_cleared_out_pct", "Cleared out of play", "%"),
            ("aer_passes_off_duel_p90", "Passes off a duel", ""),
            ("aer_prog_passes_off_duel_p90", "Prog. passes off a duel", ""),
            ("aer_shots_off_duel_p90", "Shots off a duel", ""),
            ("aer_duels_att_third_p90", "Duels, attacking third", ""),
        ],
    },
    "holdup": {
        "label": "Hold-Up Play",
        "icon": "🧱",
        "gk_only": False,
        "metrics": [
            ("hu_episodes_p90", "Episodes", ""),
            ("hu_retention_pct", "Retention", "%"),
            ("hu_prog_release_pct", "Progressive release", "%"),
            ("hu_prog_carry_pct", "Progressive carry", "%"),
            ("hu_shot_from_hold_pct", "Shot from hold", "%"),
            ("hu_fouls_won_per_hold", "Fouls won per hold", ""),
            ("hu_tackles_avoided_per_hold", "Tackles avoided", ""),
            ("hu_dangerous_loss_pct", "Dangerous loss", "%"),
        ],
    },
    "decision_making": {
        "label": "Decision Making",
        "icon": "🧠",
        "gk_only": False,
        "metrics": [
            ("dm_space_finder_pct", "Space-Finder", "%"),
            ("dm_time_bought_s", "Time Bought (approx.)", "s"),
            ("dm_shot_creator_p90", "Shot Creator", ""),
            ("dm_median_release_s", "Median release", "s"),
            ("dm_press_resist_pct", "Press Resist", "%"),
            ("dm_carry_iq_pct", "Carry IQ", "%"),
            ("dm_dribble_threat_p90", "Dribble Threat", ""),
            ("dm_tempo_setter_pct", "Tempo-Setter", "%"),
            ("dm_direct_threat_actions_p90", "Direct Threat", ""),
        ],
    },
    "final_third": {
        "label": "Final Third",
        "icon": "🎯",
        "gk_only": False,
        # Rendered specially by percentiles.py::_build_final_third_stats —
        # Completeness/Impact are cohort-relative composites, not flat
        # column lookups, so this "metrics" list isn't used directly.
        "metrics": [],
    },
}

CATEGORY_ORDER = [
    "passing", "shooting", "carrying", "half_spaces", "tempo", "decision_making",
    "final_third", "aerial", "defending", "holdup", "post_recovery", "goalkeeping",
]
